import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import styles from '@/styles/Home.module.scss'
import { Hero } from '@/components/hero/Hero'
import { About } from '@/components/about/About'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Hero/>
        <About/>

      </main>
    </>
  )
}
